// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Take a full screen HDR screenshot
Stream<CaptureResult> takeFullScreen() =>
    RustLib.instance.api.crateApiScreenShotApiTakeFullScreen();

/// Check if screen capture is supported on the current platform
Future<bool> isScreenCaptureSupported() =>
    RustLib.instance.api.crateApiScreenShotApiIsScreenCaptureSupported();

/// Get the current platform name
Future<String> getPlatformName() =>
    RustLib.instance.api.crateApiScreenShotApiGetPlatformName();

class CaptureResult {
  final String mode;
  final Uint8List rawData;
  final int frameWidth;
  final int frameHeight;

  const CaptureResult({
    required this.mode,
    required this.rawData,
    required this.frameWidth,
    required this.frameHeight,
  });

  /// Convert raw HDR buffer to Ultra HDR JPEG format
  /// This produces a backwards-compatible JPEG with embedded HDR gain map
  Future<Uint8List> toUltraHdrJpeg() =>
      RustLib.instance.api.crateApiScreenShotApiCaptureResultToUltraHdrJpeg(
        that: this,
      );

  @override
  int get hashCode =>
      mode.hashCode ^
      rawData.hashCode ^
      frameWidth.hashCode ^
      frameHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureResult &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          rawData == other.rawData &&
          frameWidth == other.frameWidth &&
          frameHeight == other.frameHeight;
}
