// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The type `Capture` is not used by any `pub` functions, thus it is ignored.
// The type `CaptureFlags` is not used by any `pub` functions, thus it is ignored.

Stream<CaptureResult> takeFullScreen({dynamic hint}) =>
    RustLib.instance.api.takeFullScreen(hint: hint);

class CaptureResult {
  final String mode;
  final Uint8List avifData;
  final Uint8List pngData;
  final int frameWidth;
  final int frameHeight;

  const CaptureResult({
    required this.mode,
    required this.avifData,
    required this.pngData,
    required this.frameWidth,
    required this.frameHeight,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      avifData.hashCode ^
      pngData.hashCode ^
      frameWidth.hashCode ^
      frameHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureResult &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          avifData == other.avifData &&
          pngData == other.pngData &&
          frameWidth == other.frameWidth &&
          frameHeight == other.frameHeight;
}
