// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CaptureResult {
  final String mode;
  final Uint8List rawData;
  final int frameWidth;
  final int frameHeight;

  const CaptureResult({
    required this.mode,
    required this.rawData,
    required this.frameWidth,
    required this.frameHeight,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      rawData.hashCode ^
      frameWidth.hashCode ^
      frameHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureResult &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          rawData == other.rawData &&
          frameWidth == other.frameWidth &&
          frameHeight == other.frameHeight;
}
